/joy_teleop:
  ros__parameters:
    slow:
      type: topic
      topic_name: cmd_vel
      message_type: geometry_msgs/msg/Twist
      deadman_buttons: [6]
      axis_mappings:
        angular-z:
          axis: 0
          offset: 0
          scale: 1.2
        linear-x:
          axis: 1
          offset: 0
          scale: 0.2

    fast:
      type: topic
      topic_name: cmd_vel
      message_type: geometry_msgs/msg/Twist
      deadman_buttons: [7]
      axis_mappings:
        angular-z:
          axis: 0
          offset: 0
          scale: 2.4
        linear-x:
          axis: 1
          offset: 0
          scale: 0.4

    dock:
      type: topic
      topic_name: dock
      message_type: std_msgs/msg/Empty
      deadman_buttons: [8]
      message_value: {}

    undock:
      type: topic
      topic_name: undock
      message_type: std_msgs/msg/Empty
      deadman_buttons: [9]
      message_value: {}
